import type { UserConfig } from '@commitlint/types';

const IGNORED_COMMIT_PATTERNS = [
  // Work in progress commits
  /^(WIP|WIP:|init|init:)/i,

  // Merge commits (auto-generated by Git)
  /^Merge (branch|remote-tracking branch|pull request)/i,

  // Revert commits (auto-generated)
  /^Revert\s+"/i,

  // Fixup and squash commits (interactive rebase)
  /^(fixup|squash)!/i,

  // Automated dependency updates
  /^(chore\(deps\)|build\(deps\)):/i,
  /^Bump\s+/i,

  // Automated version bumps
  /^(Release|Version)\s+v?\d+\.\d+\.\d+/i,
  /^chore\(release\):/i,

  // CI/Build related automated commits
  /^\[skip\s+ci\]/i,
  /^\[ci\s+skip\]/i,

  // Temporary/draft commits
  /^(tmp|temp|draft):/i,
  /^(save|checkpoint):/i
] as const;

const config: UserConfig = {
  extends: ['@commitlint/config-conventional'],
  defaultIgnores: true,
  formatter: '@commitlint/format',
  ignores: [
    (commit) => IGNORED_COMMIT_PATTERNS.some((pattern) => pattern.test(commit))
  ],
  prompt: {
    settings: {
      enableMultipleScopes: true,
      scopeEnumSeparator: ','
    },
    messages: {
      skip: ':skip',
      max: 'upper %d chars',
      min: '%d chars at least',
      emptyWarning: 'can not be empty',
      upperLimitWarning: 'over limit',
      lowerLimitWarning: 'below limit'
    },
    questions: {
      type: {
        description: "Select the type of change that you're committing:",
        enum: {
          feat: {
            description: 'A new feature',
            title: 'Features',
            emoji: '✨'
          },
          fix: {
            description: 'A bug fix',
            title: 'Bug Fixes',
            emoji: '🐛'
          },
          docs: {
            description: 'Documentation only changes',
            title: 'Documentation',
            emoji: '📚'
          },
          style: {
            description:
              'Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)',
            title: 'Styles',
            emoji: '💎'
          },
          refactor: {
            description:
              'A code change that neither fixes a bug nor adds a feature',
            title: 'Code Refactoring',
            emoji: '📦'
          },
          perf: {
            description: 'A code change that improves performance',
            title: 'Performance Improvements',
            emoji: '🚀'
          },
          test: {
            description: 'Adding missing tests or correcting existing tests',
            title: 'Tests',
            emoji: '🚨'
          },
          build: {
            description:
              'Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)',
            title: 'Builds',
            emoji: '🛠'
          },
          ci: {
            description:
              'Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)',
            title: 'Continuous Integrations',
            emoji: '⚙️'
          },
          chore: {
            description: "Other changes that don't modify src or test files",
            title: 'Chores',
            emoji: '♻️'
          },
          revert: {
            description: 'Reverts a previous commit',
            title: 'Reverts',
            emoji: '🗑'
          }
        }
      },
      scope: {
        description:
          'What is the scope of this change (e.g. component or file name)'
      },
      subject: {
        description: 'Write a short, imperative tense description of the change'
      },
      body: {
        description: 'Provide a longer description of the change'
      },
      isBreaking: {
        description: 'Are there any breaking changes?'
      },
      breakingBody: {
        description:
          'A BREAKING CHANGE commit requires a body. Please enter a longer description of the commit itself'
      },
      breaking: {
        description: 'Describe the breaking changes'
      },
      isIssueAffected: {
        description: 'Does this change affect any open issues?'
      },
      issuesBody: {
        description:
          'If issues are closed, the commit requires a body. Please enter a longer description of the commit itself'
      },
      issues: {
        description: 'Add issue references (e.g. "fix #123", "re #123".)'
      }
    }
  },
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'build', // Changes to build system or external dependencies
        'chore', // Other changes that don't modify src or test files
        'ci', // Changes to CI configuration files and scripts
        'docs', // Documentation only changes
        'feat', // A new feature
        'fix', // A bug fix
        'perf', // A code change that improves performance
        'refactor', // A code change that neither fixes a bug nor adds a feature
        'revert', // Reverts a previous commit
        'style', // Changes that don't affect the meaning of the code
        'test' // Adding missing tests or correcting existing tests
      ]
    ],
    'type-case': [2, 'always', 'lower-case'], // Type must be lowercase
    'type-empty': [2, 'never'], // Type cannot be empty
    'type-max-length': [2, 'always', 10], // Type max length is 10 characters

    // Scope validation
    'scope-case': [2, 'always', 'lower-case'], // Scope must be lowercase
    'scope-empty': [0],

    // Subject validation
    'subject-empty': [2, 'never'], // Subject cannot be empty
    'subject-full-stop': [2, 'never', '.'], // Subject cannot end with a period
    'subject-min-length': [2, 'always', 3], // Subject must be at least 3 characters
    'subject-max-length': [2, 'always', 100], // Subject max length is 100 characters

    // Header validation
    'header-max-length': [2, 'always', 90], // Header max length is 90 characters
    'header-min-length': [2, 'always', 10], // Header must be at least 10 characters

    // Body validation
    'body-leading-blank': [2, 'always'], // Body must start with blank line
    'body-max-line-length': [2, 'always', 100], // Body line max length is 100 characters
    'body-case': [0], // Disabled - body can be any case

    // Footer validation
    'footer-leading-blank': [1, 'always'], // Footer should start with blank line
    'footer-max-line-length': [2, 'always', 100], // Footer line max length is 100 characters

    // References validation
    'references-empty': [0] // Disabled - references are optional
  }
};

export default config;
